jenkinsci/gitlab-oauth-plugin

src/main/java/org/jenkinsci/plugins/GitLabRequireOrganizationMembershipACL.java

I solved adding the test condition below
```java
class GitLabRequireOrganizationMembershipACL
public boolean hasPermission(Authentication a, Permission permission) {
{
...
if (testBuildPermission(permission)) {
if (allowGitlabWebHookPermission &&
(currentUriPathStartsWith("/project/") ||
currentUriPathEquals("gitlab-webhook") ||
currentUriPathEquals("gitlab-webhook/"))) {
log.finest("Granting BUILD access for gitlab-webhook url: " + requestURI());
return true;
}
}
}
```

[JENKINS-37741] gitlab oauth plugin:GitlabAPIException

---

src/main/java/org/jenkinsci/plugins/GitLabAuthenticationToken.java

The error we observed while adding user without a group to project authorization matrix:
`java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:653)
at java.util.ArrayList.get(ArrayList.java:429)
at org.jenkinsci.plugins.GitLabAuthenticationToken.loadOrganization(GitLabAuthenticationToken.java:303)
at org.jenkinsci.plugins.GitLabSecurityRealm.loadUserByUsername(GitLabSecurityRealm.java:518)
at hudson.security.GlobalMatrixAuthorizationStrategy$DescriptorImpl.doCheckName_(GlobalMatrixAuthorizationStrategy.java:391)
at hudson.security.AuthorizationMatrixProperty$DescriptorImpl.doCheckName(AuthorizationMatrixProperty.java:198)
at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
at …

Fixed IndexOutOfBoundsException when user has no group

---

pom.xml
src/main/java/org/jenkinsci/plugins/GitLabAuthenticationToken.java
src/main/webapp/help/realm/gitlab-api-uri-help.html

This PR addresses a change from the deprecated GitLab API version 3 to version 4.
This change was necessary in order to authenticate against the latest GitLab v10.7 version.

[JENKINS-50838] Change GitLab API support from v3 to v4.

---

src/main/java/org/jenkinsci/plugins/GitLabAuthenticationToken.java
src/main/java/org/jenkinsci/plugins/GitlabRepositoryName.java

repository.isPublic() returns null while guava cache loader does NOT allow this.
These urls works fine with `gitlab-plugin` and `gitlab-auth-plugin v1.3`
```
git@www.example.com:grup/name.git
ssh://git@www.example.com:grup/name.git
www.example.com:grup/name.git
ssh://www.example.com:grup/name.git
```
After upgrade to gitlab-auth-plugin 1.4, these two DO NOT.
```
www.example.com:grup/name.git
ssh://www.example.com:grup/name.git
```

[JENKINS-52129] 1. bug fixed: repository.isPublic returns null.

---

src/main/java/org/jenkinsci/plugins/GitLabSecurityRealm.java

In presence of a reverse proxy behind jenkins the redirect url built could be wrong.
Using Jenkins.getInstance().getRootUrl() instead of request.getRequestUrl should solve the problem

Changed redirect url build using jenkins root url

---

CHANGELOG.md
README.md
docs/README.md
pom.xml

Load documentation from GitHub instead of Wiki, see https://issues.jenkins-ci.org/browse/WEBSITE-637

[WEBSITE-637] Use GitHub as source of documentation

---

README.md

Was surfing through plugins and noticed this page. Since we are going to use it as a source of plugin documnetation, maybe it makes sense to reorder it a bit to make more user-friendly
CC @zbynek

Reorder content on the README page to be more user-focused

---

src/main/java/org/jenkinsci/plugins/GitLabAuthenticationToken.java

Fix group check.
We're use Role-based Authorization Strategy and this bug produce unauthorized error on user settings page for credentials plugin button when gitlab user had groups.

Fix group and organisation check.

---

src/main/java/org/jenkinsci/plugins/GitLabAuthorizationStrategy.java
src/main/java/org/jenkinsci/plugins/GitLabRequireOrganizationMembershipACL.java
src/main/resources/org/jenkinsci/plugins/GitLabAuthorizationStrategy/config.jelly
src/main/webapp/help/auth/admin-organization-names-help.html

Great plugin - thanks for providing it.
For our project jenkins we needed the possibility to specify a gitlab group (organization) containing all admins for the jenkins (simplifies the configuration).
So I enhanced the `GitLabRequireOrganizationMembershipACL`  with the property `adminOrganizationNameList` providing exactly the wanted functionality. I tried to be conform with the rest of the code.
Would be nice to have this feature in the official plugin.
Just filed a JIRA issue (see [JENKINS-61382])

Introduces gitlab groups for admins

---

src/main/java/org/jenkinsci/plugins/GitLabAuthenticationToken.java
src/main/java/org/jenkinsci/plugins/GitLabAuthorizationStrategy.java
src/main/java/org/jenkinsci/plugins/GitLabSecurityRealm.java

As described in Gitlab's guide[1], the parameter should be included,
otherwise a default set of scopes will be granted, which seems to be
just `read_user` and is not enough for Jenkins.
According to the README, the plugin needs the `api` scope, so that's
what we're explicitly requesting from Gitlab.
[1] https://docs.gitlab.com/ee/api/oauth2.html#web-application-flow
[JENKINS-63536]
Testing: not yet, hopefully later this week. As described in the JIRA comment, manually modifying the URL fixes the issue.

Include scope in `/oauth/authorize` URL

---

src/main/java/org/jenkinsci/plugins/GitLabRequireOrganizationMembershipACL.java

Added `hudson.model.Item.Discover` to `checkReadPermission` as this permission check seems to be neccessary for authenticated (non admin) users when opening the a project details page.

added hudson.model.Item.Discover permission to read permission checks

---

src/main/java/org/jenkinsci/plugins/GitLabSecurityRealm.java

Due to the upcoming changes: https://github.com/jenkinsci/jenkins/pull/4848/files?file-filters%5B%5D=.java&hide-deleted-files=true#diff-7f1293bc6e17d8f944c084eaee7dad62R265-R279 there is an infinite loop when logging out.
Context information: https://github.com/jenkinsci/jep/tree/master/jep/227
@jglick

[JEP-227] Prevent Stackoverflow during logout

---

src/main/java/org/jenkinsci/plugins/GitLabAuthenticationToken.java

This code in `getOrganization` uses a combination of `contains` instead of checking for a strict match of the group names. If this code is called for a user in the `not-thegroup` group, `getOranization` might return `thegroup` because
```java
group.getName().contains(organization) || organization.contains(group.getName())
```
would return `true` as `"not-thegroup".contains("thegroup")` is indeed true.
I lack knowledge around the Jenkins and `hudson.security` environments to fully asses the impact of that bug but I felt like this needed to be corrected.
Let me know if I misunderstood something about the plugin!

Fix organization comparison

---

pom.xml
src/main/java/org/jenkinsci/plugins/GitLabAuthenticationToken.java
src/main/java/org/jenkinsci/plugins/GitLabOAuthGroupDetails.java

Pull request #29 broke support for nested groups.
This pull request fixes #29 and it also fixes similar namespace issue from GitLabAuthenticationToken. Update of GitLab API was dependency was required

Fix: Changed codebase to use fullPath instead of path for groups

---

pom.xml
src/main/java/org/jenkinsci/plugins/GitLabAuthenticationToken.java

See [JENKINS-66303](https://issues.jenkins.io/browse/JENKINS-66303) and [JENKINS-65988](https://issues.jenkins.io/browse/JENKINS-65988). Jenkins core is using [Guava 11.0.1](https://github.com/google/guava/releases/tag/v11.0.1), which was released on January 9, 2012. Jenkins core would like to upgrade to [Guava 30.1.1](https://github.com/google/guava/releases/tag/v30.1.1), which was released on March 19, 2021. Plugins must be prepared to be compatible with both Guava 11.0.1 and Guava 30.1.1 in advance of this core transition.
In particular, this plugin has been identified as using the `com.google.common.cache.Cache#get(K key)` API, which has been removed between Guava [11.0.1](https://guava.dev/releases/11.0.1/api/docs/com/google/common/cache/Cache.html) and …

[JENKINS-66303] Prepare Gitlab Authentication for core Guava upgrade

---

pom.xml

As an alternative to #34, just rely on the copy of this library that Jenkins core already ships.

Use SLF4J from Jenkins core

---

src/main/java/org/jenkinsci/plugins/GitLabSecurityRealm.java
src/main/resources/org/jenkinsci/plugins/GitLabSecurityRealm/config.jelly

Fixes https://issues.jenkins.io/browse/SECURITY-1891 from [security advisory](https://www.jenkins.io/security/advisory/2022-03-15/)
When serializing, the encrypted value is used. Deserialization checks if the string is in format `{encrypted}` and treats it as encrypted or plain text accordingly.
This includes changes from https://github.com/jenkinsci/gitlab-oauth-plugin/pull/58 so that the CI build can be downloaded and used for fixing both vulnerabilities.
CC @jvz @Wadeck 
- [n/a] Link to relevant pull requests, esp. upstream and downstream changes
- [n/a] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Encrypt stored client secret value

---

src/main/java/org/jenkinsci/plugins/GitLabSecurityRealm.java

Fixes https://issues.jenkins.io/browse/SECURITY-1833 from [security advisory](https://www.jenkins.io/security/advisory/2022-02-15/#SECURITY-1833)
Based on GitHub Oauth's  solution  https://github.com/jenkinsci/github-oauth-plugin/blob/master/src/main/java/org/jenkinsci/plugins/GithubSecurityRealm.java and @Wadeck 's suggestion in https://github.com/jenkinsci/gitlab-oauth-plugin/pull/17#issuecomment-1048539734
CC @jtnord @daniel-beck 
- [?] Ensure you have provided tests - that demonstrates feature works or fixes the issue
I didn't add any tests because I couldn't find any tests in thi repo. Setting them up is non-trivial because a mock implementation of GitLab is needed.

Store redirect URL in a session variable

---

src/main/java/org/jenkinsci/plugins/GitLabSecurityRealm.java

Amends #59 -- there I removed the getter (assuming it was better not to expose the secret via public method), but it's needed for the Jelly controls to work correctly. Without it, clicking "save" in global configuration without making any changes will store empty secret to config, locking everybody out. Sorry for the mess!
@basil could you please release this soon?

Add client secret getter for jelly

---

pom.xml
src/main/java/org/jenkinsci/plugins/GitLabAuthenticationException.java
src/main/java/org/jenkinsci/plugins/GitLabAuthenticationToken.java
src/main/java/org/jenkinsci/plugins/GitLabAuthorizationStrategy.java
src/main/java/org/jenkinsci/plugins/GitLabLogoutAction.java
src/main/java/org/jenkinsci/plugins/GitLabOAuthGroupDetails.java
src/main/java/org/jenkinsci/plugins/GitLabOAuthScope.java
src/main/java/org/jenkinsci/plugins/GitLabOAuthUserDetails.java
src/main/java/org/jenkinsci/plugins/GitLabRequireOrganizationMembershipACL.java
src/main/java/org/jenkinsci/plugins/GitLabSecurityRealm.java
src/main/java/org/jenkinsci/plugins/GitlabRepositoryName.java

The config is reused from Jenkins core.
- [n/a] Link to relevant issues in GitHub or Jira
- [n/a] Link to relevant pull requests, esp. upstream and downstream changes
- [n/a] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Add checkstyle config, fix warnings

---

pom.xml
src/main/java/org/jenkinsci/plugins/GitLabAuthenticationToken.java
src/main/java/org/jenkinsci/plugins/GitLabOAuthGroupDetails.java
src/main/java/org/jenkinsci/plugins/GitLabOAuthUserDetails.java
src/main/java/org/jenkinsci/plugins/GitLabSecurityRealm.java

Using the new `gitlab-api` plugin from https://github.com/jenkinsci/gitlab-api-plugin/pull/7
It took a while to get this compile. I have not tried to run the code and I do not have a GitLab server to test with.
Anyone interested in testing this? @zbynek perhaps since you submitted some security fixes recently (no pressure, though)? @dcendents since you're doing other GitLab plugin stuff?

Use `gitlab-api` plugin

---

pom.xml
src/main/java/org/jenkinsci/plugins/GitLabAuthenticationToken.java
src/main/java/org/jenkinsci/plugins/GitLabOAuthUserDetails.java
src/main/java/org/jenkinsci/plugins/GitLabSecurityRealm.java
src/spotbugs/excludesFilter.xml

Resolve 2 spotbugs issues and increase spotbugs checks

---

pom.xml

Updated the Jenkins version to 2.387.3 in `pom.xml` as suggested by https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/#changing-the-minimum-required-version.

Update Jenkins version to 2.387.3 in pom.xml

---

src/main/java/org/jenkinsci/plugins/GitLabSecurityRealm.java

it's not compatible with gitlab-ce 12.5, gitlab will return 401 when trying to get access_token.
I tested it with gitlab 12.5 and 16.1
```[tasklist]
```

remove useless char "?" at the end of redirect_uri

---

.github/dependabot.yml
pom.xml

- Use checkstyle 10 now that we require Java 11
- Label dependabot pull requests
The checkstyle output continues silent when I run `mvn checkstyle:checkstyle`.  Will confirm with ci.jenkins.io as well.

Use checkstyle for Java 11

---

pom.xml

The bom version should generally match the line associated with the Jenkins minimum version.
Confirmed that tests pass on Java 21.

Match bom version with min Jenkins version
